name: Build and Upload HTML Application to S3

# Run the workflow on every push to the main branch or on pull requests
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@master

      # Step 2: Install zip utility
      - name: Install zip
        run: sudo apt-get install zip -y

      # Step 3: Archive the HTML application (index.html) into a zip file
      - name: Package HTML application into zip
        run: |
          mkdir -p output
          zip -r output/html-application-$(date +'%Y-%m-%d_%H-%M-%S').zip index.html

      # Step 4: Upload the zip archive to AWS S3
      - name: Upload artifact to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ACCESS_KE_ID }}
          AWS_REGION: 'ap-southeast-1'
          SOURCE_DIR: 'exam'
